# Generated by Django 5.0.14 on 2026-07-19 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Обложка')),
                ('preview_audio', models.FileField(upload_to='audio_previews/', verbose_name='Превью (для прослушивания)')),
                ('full_audio', models.FileField(upload_to='audio_full/', verbose_name='Полный файл (для скачивания)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Бит',
                'verbose_name_plural': 'Биты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('telegram', models.CharField(max_length=150, verbose_name='Telegram')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='beats.beat')),
                ('user', models.ForeignKey(blank=True, help_text='Если человек был залогинен в момент скачивания', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на скачивание',
                'verbose_name_plural': 'Заявки на скачивание',
                'ordering': ['-created_at'],
            },
        ),
    ]
